package com.eco.system.entity;

import java.time.LocalDate;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PastOrPresent;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing an Order in the system.
 * Maps to the 'orders' table in the database.
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "orders")
public class Order {

    /**
     * Primary key of the Order entity.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer orderId;

    /**
     * The customer who placed the order.
     * This field is mandatory and maps to the 'customer_id' column.
     */
    @NotNull(message = "Customer is mandatory")
    @ManyToOne
    @JoinColumn(name = "customer_id")
    private Customer customer;

    /**
     * The product that was ordered.
     * This field is mandatory and maps to the 'product_id' column.
     */
    @NotNull(message = "Product is mandatory")
    @ManyToOne
    @JoinColumn(name = "product_id")
    private Product product;

    /**
     * The quantity of the product ordered.
     * Must be at least 1 and cannot be null.
     */
    @NotNull(message = "Quantity is mandatory")
    @Min(value = 1, message = "Quantity must be at least 1")
    private Integer quantity;

    /**
     * The total price for the order.
     * Must be non-negative and cannot be null.
     */
    @NotNull(message = "Total Price is mandatory")
    @Min(value = 0, message = "Total Price must be non-negative")
    private Integer totalPrice;

    /**
     * The status of the order.
     * This field is mandatory.
     * Consider using an enumeration or validating against a set of predefined statuses.
     */
    @NotNull(message = "Status is mandatory")
    // @Pattern(regexp = "Pending|Shipped|Delivered|Cancelled", message = "Status must be one of the following: Pending, Shipped, Delivered, Cancelled")
    private String status;

    /**
     * The date when the order was placed.
     * Must be in the past or present and cannot be null.
     */
    @NotNull(message = "Order Date is mandatory")
    @PastOrPresent(message = "Order Date cannot be in the future")
    private LocalDate orderDate;
}
