package com.eco.system.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing a Product in the system.
 * Maps to the 'products' table in the database.
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "products")
public class Product {

    /**
     * Primary key of the Product entity.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer productId;

    /**
     * The name of the product.
     * This field is mandatory and must be between 2 and 100 characters.
     */
    @NotBlank(message = "Product name is mandatory")
    @Size(min = 2, max = 100, message = "Product name must be between 2 and 100 characters")
    private String productName;

    /**
     * The category of the product.
     * This field is mandatory and must be between 2 and 50 characters.
     */
    @NotBlank(message = "Category is mandatory")
    @Size(min = 2, max = 50, message = "Category must be between 2 and 50 characters")
    private String category;

    /**
     * The price of the product.
     * This field is mandatory and must be a non-negative integer.
     */
    @NotNull(message = "Price is mandatory")
    @Min(value = 0, message = "Price must be a positive value")
    private Integer price;

    /**
     * The stock quantity of the product.
     * This field is mandatory and must be a non-negative integer.
     */
    @NotNull(message = "Stock is mandatory")
    @Min(value = 0, message = "Stock must be a positive value")
    private Integer stock;

    /**
     * Constructor to initialize a Product with an ID.
     * This is useful for creating Product instances with only an ID.
     */
    public Product(Integer productId) {
        super();
        this.productId = productId;
    }
}
